### ISSUE TITLE
Accessing Languages with - or _ in URI. 

### ISSUE THREAD

**Issue by skny5** [mikehaertl/localeurls#1]
Hey Mike,

I was using your extension on a project and noticed that languages with a "-" or "_" in them brings up a 404 error: "Unable to resolve the request -ca", this was attempting to use en-ca or en_ca. 

I've added the supported languages to the config array/
'languages' => array('en_us','en','de','fr','en_ca','en_gb'),

Is there a preferred format to enter the supported languages? Thanks for your help.

Best,
Sean

**Comment by mikehaertl** [comment]
Hi,

you only have to change the order so that `en_gb` is listed before `en` in your `languages` array. Also see the note in the Installation section in the README.
