### ISSUE TITLE
LocaleHttpRequest.preferredLanguages not defined

### ISSUE THREAD

**Issue by ps202** [mikehaertl/localeurls#12]
Hi,

I always get this error message:
LocaleHttpRequest.preferredLanguages is not defined...

Could someone help?

Thanks in advance!

**Comment by mikehaertl** [comment]
Not sure, what you did, but you will not find `preferredLanguages` anywhere in this codebase. So unless you provide some more of your code and configuration I can't help you.

**Comment by mikehaertl** [comment]
Correcting myself: You _do_ find it, but in an outdated version:
https://github.com/mikehaertl/localeurls/blob/3e3c011833e91a18a90675331ddd7e9740411549/LocaleHttpRequest.php#L133

You should update to the latest version.

**Comment by ps202** [comment]
Hi,

I solved the issue.

Thanks!
